### ISSUE TITLE
Support changing configuration file path

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-action-tfsec#59]
https://github.com/suzuki-shunsuke/tfaction/issues/246

```yaml
- uses: suzuki-shunsuke/github-action-tfsec@v0.1.1
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    working_directory: foo
```

https://aquasecurity.github.io/tfsec/v1.6.2/getting-started/configuration/config/

```yaml
- uses: suzuki-shunsuke/github-action-tfsec@main
  with:
    config_paths:
    - tfsec.yaml
    - ../tfsec.yaml
```

```yaml
- uses: suzuki-shunsuke/github-action-tfsec@main
  with:
    config_names: # search configuration files recursively
    - tfsec.yaml
    - tfsec.json
    - tfsec.yml
```
